In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [2]:
df=pd.read_csv("C:\\Users\\manzo\\Downloads\\archive (8)\\Credit Score Classification Dataset.csv")
df


Age  Gender  Income            Education Marital Status  \
0     25  Female   50000    Bachelor's Degree         Single   
1     30    Male  100000      Master's Degree        Married   
2     35  Female   75000            Doctorate        Married   
3     40    Male  125000  High School Diploma         Single   
4     45  Female  100000    Bachelor's Degree        Married   
..   ...     ...     ...                  ...            ...   
159   29  Female   27500  High School Diploma         Single   
160   34    Male   47500   Associate's Degree         Single   
161   39  Female   62500    Bachelor's Degree        Married   
162   44    Male   87500      Master's Degree         Single   
163   49  Female   77500            Doctorate        Married   

     Number of Children Home Ownership Credit Score  
0                     0         Rented         High  
1                     2          Owned         High  
2                     1          Owned         High  
3                     0          Owned         High  
4                     3          Owned         High  
..                  ...            ...          ...  
159                   0         Rented          Low  
160                   0         Rented      Average  
161                   2          Owned         High  
162                   0          Owned         High  
163                   1          Owned         High  

[164 rows x 8 columns]

In [3]:

df.head()


Age  Gender  Income            Education Marital Status  \
0   25  Female   50000    Bachelor's Degree         Single   
1   30    Male  100000      Master's Degree        Married   
2   35  Female   75000            Doctorate        Married   
3   40    Male  125000  High School Diploma         Single   
4   45  Female  100000    Bachelor's Degree        Married   

   Number of Children Home Ownership Credit Score  
0                   0         Rented         High  
1                   2          Owned         High  
2                   1          Owned         High  
3                   0          Owned         High  
4                   3          Owned         High

In [4]:
df.tail()

Age  Gender  Income            Education Marital Status  \
159   29  Female   27500  High School Diploma         Single   
160   34    Male   47500   Associate's Degree         Single   
161   39  Female   62500    Bachelor's Degree        Married   
162   44    Male   87500      Master's Degree         Single   
163   49  Female   77500            Doctorate        Married   

     Number of Children Home Ownership Credit Score  
159                   0         Rented          Low  
160                   0         Rented      Average  
161                   2          Owned         High  
162                   0          Owned         High  
163                   1          Owned         High

In [5]:
df.shape

(164, 8)

In [6]:
df.dtypes

Age                    int64
Gender                object
Income                 int64
Education             object
Marital Status        object
Number of Children     int64
Home Ownership        object
Credit Score          object
dtype: object

In [7]:
df.isnull().sum()

Age                   0
Gender                0
Income                0
Education             0
Marital Status        0
Number of Children    0
Home Ownership        0
Credit Score          0
dtype: int64

In [8]:

df.columns

Index(['Age', 'Gender', 'Income', 'Education', 'Marital Status',
       'Number of Children', 'Home Ownership', 'Credit Score'],
      dtype='object')

In [9]:
from sklearn.preprocessing import LabelEncoder
lab=LabelEncoder()
df['Gender']=lab.fit_transform(df['Gender'])
df

Age  Gender  Income            Education Marital Status  \
0     25       0   50000    Bachelor's Degree         Single   
1     30       1  100000      Master's Degree        Married   
2     35       0   75000            Doctorate        Married   
3     40       1  125000  High School Diploma         Single   
4     45       0  100000    Bachelor's Degree        Married   
..   ...     ...     ...                  ...            ...   
159   29       0   27500  High School Diploma         Single   
160   34       1   47500   Associate's Degree         Single   
161   39       0   62500    Bachelor's Degree        Married   
162   44       1   87500      Master's Degree         Single   
163   49       0   77500            Doctorate        Married   

     Number of Children Home Ownership Credit Score  
0                     0         Rented         High  
1                     2          Owned         High  
2                     1          Owned         High  
3                     0          Owned         High  
4                     3          Owned         High  
..                  ...            ...          ...  
159                   0         Rented          Low  
160                   0         Rented      Average  
161                   2          Owned         High  
162                   0          Owned         High  
163                   1          Owned         High  

[164 rows x 8 columns]

In [10]:
df['Education']=lab.fit_transform(df['Education'])
df


Age  Gender  Income  Education Marital Status  Number of Children  \
0     25       0   50000          1         Single                   0   
1     30       1  100000          4        Married                   2   
2     35       0   75000          2        Married                   1   
3     40       1  125000          3         Single                   0   
4     45       0  100000          1        Married                   3   
..   ...     ...     ...        ...            ...                 ...   
159   29       0   27500          3         Single                   0   
160   34       1   47500          0         Single                   0   
161   39       0   62500          1        Married                   2   
162   44       1   87500          4         Single                   0   
163   49       0   77500          2        Married                   1   

    Home Ownership Credit Score  
0           Rented         High  
1            Owned         High  
2            Owned         High  
3            Owned         High  
4            Owned         High  
..             ...          ...  
159         Rented          Low  
160         Rented      Average  
161          Owned         High  
162          Owned         High  
163          Owned         High  

[164 rows x 8 columns]

In [11]:
df['Marital Status']=lab.fit_transform(df['Marital Status'])
df

Age  Gender  Income  Education  Marital Status  Number of Children  \
0     25       0   50000          1               1                   0   
1     30       1  100000          4               0                   2   
2     35       0   75000          2               0                   1   
3     40       1  125000          3               1                   0   
4     45       0  100000          1               0                   3   
..   ...     ...     ...        ...             ...                 ...   
159   29       0   27500          3               1                   0   
160   34       1   47500          0               1                   0   
161   39       0   62500          1               0                   2   
162   44       1   87500          4               1                   0   
163   49       0   77500          2               0                   1   

    Home Ownership Credit Score  
0           Rented         High  
1            Owned         High  
2            Owned         High  
3            Owned         High  
4            Owned         High  
..             ...          ...  
159         Rented          Low  
160         Rented      Average  
161          Owned         High  
162          Owned         High  
163          Owned         High  

[164 rows x 8 columns]

In [12]:
df['Home Ownership']=lab.fit_transform(df['Home Ownership'])
df

Age  Gender  Income  Education  Marital Status  Number of Children  \
0     25       0   50000          1               1                   0   
1     30       1  100000          4               0                   2   
2     35       0   75000          2               0                   1   
3     40       1  125000          3               1                   0   
4     45       0  100000          1               0                   3   
..   ...     ...     ...        ...             ...                 ...   
159   29       0   27500          3               1                   0   
160   34       1   47500          0               1                   0   
161   39       0   62500          1               0                   2   
162   44       1   87500          4               1                   0   
163   49       0   77500          2               0                   1   

     Home Ownership Credit Score  
0                 1         High  
1                 0         High  
2                 0         High  
3                 0         High  
4                 0         High  
..              ...          ...  
159               1          Low  
160               1      Average  
161               0         High  
162               0         High  
163               0         High  

[164 rows x 8 columns]

In [26]:
x=df.iloc[:,:-1]
x

Age  Gender  Income  Education  Marital Status  Number of Children  \
0     25       0   50000          1               1                   0   
1     30       1  100000          4               0                   2   
2     35       0   75000          2               0                   1   
3     40       1  125000          3               1                   0   
4     45       0  100000          1               0                   3   
..   ...     ...     ...        ...             ...                 ...   
159   29       0   27500          3               1                   0   
160   34       1   47500          0               1                   0   
161   39       0   62500          1               0                   2   
162   44       1   87500          4               1                   0   
163   49       0   77500          2               0                   1   

     Home Ownership  
0                 1  
1                 0  
2                 0  
3                 0  
4                 0  
..              ...  
159               1  
160               1  
161               0  
162               0  
163               0  

[164 rows x 7 columns]

In [27]:
y=df.iloc[:,-1]
y

0         High
1         High
2         High
3         High
4         High
        ...   
159        Low
160    Average
161       High
162       High
163       High
Name: Credit Score, Length: 164, dtype: object

In [28]:

x.ndim

2

In [29]:

y.ndim

1

In [30]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)
x_train

Age  Gender  Income  Education  Marital Status  Number of Children  \
97    45       0  115000          1               0                   3   
11    51       1  135000          1               0                   0   
65    45       0  110000          1               0                   3   
86    34       1   47500          0               1                   0   
6     26       0   40000          0               1                   0   
..   ...     ...     ...        ...             ...                 ...   
71    46       0   97500          3               0                   1   
106   32       1   57500          0               1                   0   
14    37       0   70000          1               0                   2   
92    35       0   85000          2               0                   1   
102   41       1  120000          2               1                   0   

     Home Ownership  
97                0  
11                0  
65                0  
86                1  
6                 1  
..              ...  
71                0  
106               1  
14                0  
92                0  
102               0  

[114 rows x 7 columns]

In [31]:
y_test

135    Average
115       High
131    Average
55        High
95        High
29     Average
157       High
51        High
101       High
145       High
19     Average
85         Low
15        High
66        High
24         Low
30        High
132       High
105        Low
152       High
16        High
75        High
18         Low
12         Low
9         High
31        High
155       High
98        High
56        High
134       High
160    Average
139       High
78        High
60        High
84        High
2         High
94        High
45        High
42     Average
69        High
153        Low
26        High
141    Average
117        Low
93     Average
133    Average
36     Average
82        High
22        High
126       High
67     Average
Name: Credit Score, dtype: object

In [32]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_train

array([[ 0.77593283, -1.05409255,  0.90243185, -0.73865505, -0.98260737,
         2.66391337, -0.66561098],
       [ 1.49704432,  0.9486833 ,  1.5267816 , -0.73865505, -0.98260737,
        -0.69792564, -0.66561098],
       [ 0.77593283, -1.05409255,  0.74634441, -0.73865505, -0.98260737,
         2.66391337, -0.66561098],
       [-0.5461049 ,  0.9486833 , -1.20474857, -1.45227095,  1.01770049,
        -0.69792564,  1.50237907],
       [-1.50758688, -1.05409255, -1.43887973, -1.45227095,  1.01770049,
        -0.69792564,  1.50237907],
       [ 0.65574758,  0.9486833 , -0.34626766,  1.40219264,  1.01770049,
        -0.69792564, -0.66561098],
       [ 0.41537709,  0.9486833 ,  0.59025697,  1.40219264,  1.01770049,
        -0.69792564, -0.66561098],
       [-0.90666064,  0.9486833 , -0.65844254, -0.73865505,  1.01770049,
        -0.69792564,  1.50237907],
       [ 0.29519184,  0.9486833 ,  0.74634441, -0.02503915,  1.01770049,
        -0.69792564, -0.66561098],
       [-1.38740164, -1.0540

# KNN,Naivebayes,SVM algorithms


In [34]:
from sklearn.neighbors import KNeighborsClassifier

In [35]:
KNC=KNeighborsClassifier()

In [36]:
KNC.fit(x_train,y_train)

KNeighborsClassifier()

In [37]:
pred=KNC.predict(x_test)

In [42]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [43]:

accuracy = accuracy_score(y_test, pred)
conf_matrix = confusion_matrix(y_test, pred)
classification_rep = classification_report(y_test, pred)

print(f'Accuracy: {accuracy:.2f}')
print(f'Confusion Matrix:\n{conf_matrix}')
print(f'Classification Report:\n{classification_rep}')


Accuracy: 0.92
Confusion Matrix:
[[ 9  2  0]
 [ 2 30  0]
 [ 0  0  7]]
Classification Report:
              precision    recall  f1-score   support

     Average       0.82      0.82      0.82        11
        High       0.94      0.94      0.94        32
         Low       1.00      1.00      1.00         7

    accuracy                           0.92        50
   macro avg       0.92      0.92      0.92        50
weighted avg       0.92      0.92      0.92        50



In [44]:
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
n_model=GaussianNB()
s_model=SVC()
lst=[n_model,s_model]


In [45]:
from sklearn.metrics import accuracy_score

for i, model in enumerate(lst):
    model.fit(x_train, y_train)  # Train each classifier
    y_pred = model.predict(x_test)  # Predict labels for test data
    accuracy = accuracy_score(y_test, y_pred)  # Compute accuracy
    print(f"Accuracy of model {i+1}: {accuracy:.4f}")

Accuracy of model 1: 0.9000
Accuracy of model 2: 0.9000


In [46]:
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy:.2f}')
print(f'Confusion Matrix:\n{conf_matrix}')
print(f'Classification Report:\n{classification_rep}')


Accuracy: 0.90
Confusion Matrix:
[[ 9  2  0]
 [ 1 31  0]
 [ 2  0  5]]
Classification Report:
              precision    recall  f1-score   support

     Average       0.75      0.82      0.78        11
        High       0.94      0.97      0.95        32
         Low       1.00      0.71      0.83         7

    accuracy                           0.90        50
   macro avg       0.90      0.83      0.86        50
weighted avg       0.91      0.90      0.90        50



# RandomForestClassifier

In [47]:
from sklearn.ensemble import RandomForestClassifier

In [48]:
rfc=RandomForestClassifier()

In [49]:
rfc.fit(x_train,y_train)

RandomForestClassifier()

In [50]:
pred3=rfc.predict(x_test)

In [51]:

accuracy = accuracy_score(y_test, pred3)
conf_matrix = confusion_matrix(y_test, pred3)
classification_rep = classification_report(y_test, pred3)

print(f'Accuracy: {accuracy:.2f}')
print(f'Confusion Matrix:\n{conf_matrix}')
print(f'Classification Report:\n{classification_rep}')


Accuracy: 0.94
Confusion Matrix:
[[ 9  2  0]
 [ 1 31  0]
 [ 0  0  7]]
Classification Report:
              precision    recall  f1-score   support

     Average       0.90      0.82      0.86        11
        High       0.94      0.97      0.95        32
         Low       1.00      1.00      1.00         7

    accuracy                           0.94        50
   macro avg       0.95      0.93      0.94        50
weighted avg       0.94      0.94      0.94        50

